FROM --platform=linux/arm64 python:3.13-slim

WORKDIR /app

COPY ./pyproject.toml /app/
COPY ./uv.lock /app/

RUN pip install --upgrade pip && pip install uv
RUN uv pip install --system .

CMD ["flask", "run", "-h", "0.0.0.0"]