FROM --platform=linux/arm64 python:3.11-slim-bullseye

WORKDIR /app

RUN mkdir -p /var/cache/apt/archives/partial \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
     gcc \
     unixodbc-dev \
     libsasl2-dev \
  && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /app/

RUN pip install --upgrade pip \
  && pip install -r requirements.txt

COPY ./client/ /app/

CMD ["flask", "run", "-h", "0.0.0.0"]